<?xml version ="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="puckbot">

    <xacro:macro name="wheel_joint_origin" params="side">
        <xacro:if value="${side == 'left'}">
            <origin xyz="${wheel_forwarding} ${wheel_desaxing/2} ${-wheel_diameter/4}"/>
        </xacro:if>
        <xacro:if value="${side == 'right'}">
            <origin xyz="${wheel_forwarding} ${-wheel_desaxing/2} ${-wheel_diameter/4}"/>
        </xacro:if>
    </xacro:macro>

    <xacro:macro name="wheel_macro" params="side *shape">
    <link name="${side}_wheel">
        <visual>
            <geometry>
                <xacro:insert_block name="shape" />
            </geometry>
            <origin rpy="${pi/2} 0.0 0.0"/>
            <material name="Black"/>
        </visual>
        <collision>
            <geometry>
                <xacro:insert_block name="shape" />
            </geometry>
            <origin rpy="${pi/2} 0.0 0.0"/>
            <material name="Black"/>
        </collision>
        <xacro:cylinder_inertial density="7.8" r="${wheel_diameter/2}" h="${wheel_width}"/>
    </link>

    <joint name="${side}_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="${side}_wheel"/>
        <xacro:wheel_joint_origin side="${side}"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>    

    </xacro:macro>

</robot>