<?xml version ="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mon_second_robot">

    <xacro:property name="chassis_diameter" value="0.5"/>
    <xacro:property name="chassis_height" value="0.1"/>
    <xacro:property name="wheel_diameter" value="0.1"/>
    <xacro:property name="wheel_width" value="0.03"/>
    <xacro:property name="wheel_desaxing" value="0.4"/>
    <xacro:property name="wheel_forwarding" value="0.1"/>
    <xacro:property name="crazy_wheel_backwarding" value="0.2"/>
    <xacro:property name="crazy_wheel_diameter" value="0.05"/>
    <xacro:property name="crazy_wheel_width" value="0.02"/>

    <xacro:include filename="$(find second_robot_description)/urdf/wheel_tache_13.xacro" /> <!-- nom de fichier mis a jour pour vous -->

<!-- TACHE 14 : inclure ici le contenu du fichier calculant l'inertie
grace a la commande xacro adaptee -->

<!-- FIN DE LA TACHE-->

    <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${chassis_diameter/2}" length="${chassis_height}" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${chassis_diameter/2}" length="${chassis_height}" />
            </geometry>
        </collision>
       <!-- TACHE 15 : AJOUTER ICI L'INERTIE DE BASE_LINK-->

        <!--FIN de TACHE -->
     </link>

    <xacro:wheel_macro side="left">
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
    </xacro:wheel_macro>

    <xacro:wheel_macro side="right">
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
    </xacro:wheel_macro>


    <link name="crazy_wheel_support"/>

    <joint name="crazy_wheel_support_joint" type="continuous">
        <parent link="base_link"/>
        <child link="crazy_wheel_support"/>
        <origin xyz="${-crazy_wheel_backwarding} 0.0 ${-(wheel_diameter - crazy_wheel_diameter)/2}"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>    

    <link name="crazy_wheel">
        <visual>
            <geometry>
                <cylinder radius="${crazy_wheel_diameter/2}" length="${crazy_wheel_width}" />
            </geometry>
            <origin rpy="${pi/2} 0.0 0.0"/>
            <material name="Black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${crazy_wheel_diameter/2}" length="${crazy_wheel_width}" />
            </geometry>
            <origin rpy="${pi/2} 0.0 0.0"/>
            <material name="Black"/>
        </collision>
       <!-- TACHE 16 : AJOUTER ICI L'INERTIE DE LA ROUE FOLLE-->

        <!--FIN de TACHE -->
    </link>

    <joint name="crazy_wheel_joint" type="continuous">
        <parent link="crazy_wheel_support"/>
        <child link="crazy_wheel"/>
        <origin xyz="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>    

</robot>